### ISSUE TITLE
Install failure

### ISSUE THREAD

**Issue by jmalko** [arthurperton/statamic-wordpress-users#1]
## Bug description
Attempt to install via button and composer results in failure.

## How to Reproduce
Here is a log from an attempt at installing through composer

jmalko@LAPTOP-H24MQPTM:~/afterschool$ composer require arthurperton/wordpress-users
Using version ^1.0 for arthurperton/wordpress-users
./composer.json has been updated
Running composer update arthurperton/wordpress-users
> Statamic\Console\Composer\Scripts::preUpdateCmd
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Downloading hautelook/phpass (1.1.0)
 0/1 [>---------------------------]   0%    Failed to download hautelook/phpass from dist: The "https://api.github.com/repos/hautelook/phpass/zipball/b2daca28508000d1dd126e93ec472d771626a774" file could not be downloaded (HTTP/2 404 ):
{"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/repos#download-a-repository-archive"}
    Now trying to download from source
  - Syncing hautelook/phpass (1.1.0) into cache
 1/1 [============================] 100%

  [RuntimeException]
  Failed to execute git clone --mirror -- 'https://ghp...Xuv:x-oauth-basic@github.com/hautelook/phpass.git' '/home/jmalko/.cache/composer/vcs/https---github.com-hautelook-phpas
  s.git/'

  Cloning into bare repository '/home/jmalko/.cache/composer/vcs/https---github.com-hautelook-phpass.git'...
  remote: Repository not found.
  fatal: repository 'https://github.com/hautelook/phpass.git/' not found

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-scripts] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>]...

## Environment

Statamic 3.2.24 Pro
Laravel 8.74.0
PHP 8.0.13
aryehraber/statamic-impersonator 2.3.1

**Install method for Statamic (choose one):**
- Fresh install from `statamic/statamic`

**Comment by arthurperton** [comment]
Thanks for the bug report @jmalko !

There is a fix for this, which I'll try and apply soon.

It seems like one of the dependencies (`hautelook/phpass`) is no longer available. There are other copies (forks) available though. Maybe I'll fork it myself, to make sure this doesn't happen again.

**Comment by arthurperton** [comment]
The issue has been fixed in the latest release (v1.0.3). Closing the issue now. I'd be happy to hear about your experience with the add-on!

**Comment by jmalko** [comment]
Thanks so much @arthurperton !

**Comment by arthurperton** [comment]
You're welcome!
